apiVersion: v1
kind: ServiceAccount
metadata:
  name: solsa-transformer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: solsa-transformer
subjects:
- kind: ServiceAccount
  name: solsa-transformer
roleRef:
  kind: Role
  name: solsa-transformer
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: solsa-transformer
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create"]
