apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - port: 8080
  selector:
    solsa.ibm.com/pod: hello-world
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      solsa.ibm.com/pod: hello-world
  template:
    metadata:
      labels:
        solsa.ibm.com/pod: hello-world
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: docker.io/ibmcom/kn-helloworld
        livenessProbe:
          tcpSocket:
            port: 8080
        name: hello-world
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
spec:
  rules:
  - host: hello-world.mycluster123.us-east.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - hello-world.mycluster123.us-east.containers.appdomain.cloud
    secretName: mycluster123
