apiVersion: v1
kind: Service
metadata:
  labels:
    solsa.ibm.com/name: hello-world
  name: hello-world
spec:
  ports:
  - name: http
    port: 8080
  selector:
    solsa.ibm.com/name: hello-world
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    solsa.ibm.com/name: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      solsa.ibm.com/name: hello-world
  template:
    metadata:
      labels:
        solsa.ibm.com/name: hello-world
    spec:
      containers:
      - env: []
        image: docker.io/ibmcom/kn-helloworld
        name: hello-world
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    solsa.ibm.com/name: hello-world
  name: hello-world-ing-iks
spec:
  rules:
  - host: hello-world.mycluster123.us-east.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: http
        path: /
  tls:
  - hosts:
    - hello-world.mycluster123.us-east.containers.appdomain.cloud
    secretName: mycluster123
